import { yamlString } from "./markdown-text.ts";

export interface GeneratedPage {
  readonly path: string;
  readonly text: string;
}

export interface PageFields {
  readonly source: string;
  readonly title: string;
  readonly description: string;
  readonly order: number;
  readonly label?: string;
  readonly body: string;
}

export const GENERATE_COMMAND = "pnpm --filter @house-rules/site generate";

export const generatedPage = (path: string, fields: PageFields): GeneratedPage => ({
  path,
  text: [
    "---",
    `# Generated by site/scripts/generate.ts from ${fields.source}. Do not edit. Run: ${GENERATE_COMMAND}`,
    `title: ${yamlString(fields.title)}`,
    `description: ${yamlString(fields.description)}`,
    "sidebar:",
    `  order: ${fields.order}`,
    ...(fields.label === undefined ? [] : [`  label: ${yamlString(fields.label)}`]),
    "---",
    "",
    fields.body.trim(),
    "",
  ].join("\n"),
});
